version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-stretch

    working_directory: ~/repo

    steps:
      - checkout
      
      - run: git clone https://github.com/HalleyAssist/node --branch v12-draft-22

      - run: |
          cd quic
          ./configure
          make -j3
          zip -r ~/repo/quic.zip ~/repo/quic

      - store_artifacts:
          path: ~/repo/quic.zip
          destination: quic.zip
